---
kind: Config
apiVersion: v1
preferences: {}
clusters:
- name: gitlab-authn
  cluster:
    server: http://localhost:3000/authenticate
users:
- name: authn-apiserver
  user:
    token: secret
contexts:
- name: webhook
  context:
    cluster: gitlab-authn
    user: authn-apiserver
current-context: webhook
